### ISSUE TITLE
Trainable v/s Non-Trainable Parameters

### ISSUE THREAD

**Issue by nipunbatra** [sustainability-lab/ASTRA#2]
We can have a different number of trainable and non-trainable parameters. Sometimes, we need to account for both (e.g. transfer learning with frozen layers).

https://github.com/sustainability-lab/SusML/blob/ddcd51871fbaceec585fd9e334075c99108f0f70/susml/torch/utils.py#L7

**Comment by AYUSHs799** [comment]
The function in question currently calculates all the trainable parameters (Parameters having 'requires_grad' = True). Similarly, we can also calculate all the non-trainable parameters by counting all params having 'requires_grad' = False. 

```py
trainable = sum(p.numel() for p in model.parameters() if p.requires_grad)
non-trainable = sum(p.numel() for p in model.parameters() if not(p.requires_grad))
```

What is the function expected to return? Just the total count? Or Do we expect it to return the trainable and non-trainable parameters count for every layer? Something similar to `torchinfo summary` method.

**Comment by patel-zeel** [comment]
This issue is resolved now.

https://github.com/sustainability-lab/ASTRA/blob/414b105ebff370baca81b990040ef49eb51b1598/README.md?plain=1#L308-L323
