### ISSUE TITLE
[Adding additional information in Bug report template]

### ISSUE THREAD

**Issue by nipunbatra** [sustainability-lab/ASTRA#21]
We can add the following in addition to the instructions given in the bug template.

```py
import sys
sys.version
```

`'3.9.7 | packaged by conda-forge | (default, Sep 29 2021, 19:20:46) \n[GCC 9.4.0]'`

```py
import astra
astra.__version__
```

**Comment by patel-zeel** [comment]
Added this in https://github.com/sustainability-lab/ASTRA/commit/dcb6aaef29ac827c0bb1cd122e0ceb2d111a4b66
